name: MAUICodes

on:
  push:
    branches:
      - master
    paths:
      - 'src/MauiCodes/**'
      - '!src/MauiCodes/readme.md'
      
jobs:

  build:

    name: Build
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src/MauiCodes

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Publish Nuget package
      run: dotnet nuget push bin/Release/MauiCodes.*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
