name: MAUIDays

on:
  push:
    branches:
      - master
    paths:
      - 'src/MauiDays/**'
      - '!src/MauiDays/readme.md'
      
jobs:

  build:

    name: Build
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src/MauiDays

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Get Nuget package name
      run: dir /s MauiDays.*.nupkg /b > result.txt
      
    - name: Save on a temporary variable
      run: set /p PACKAGENAMETOPUBLISH=<result.txt

    - name: Publish Nuget package
      run: dotnet nuget push %PACKAGENAMETOPUBLISH% --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
