name: MAUIDays

on:
  push:
    branches:
      - master
    paths:
      - 'src/MauiDays/**'
      - '!src/MauiDays/readme.md'
      
jobs:

  build:

    name: Build
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src/MauiDays

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Get Nuget package name
      shell: powershell
      run: |
          cmd /r dir /s MauiDays.*.nupkg /b > result.txt
          Get-Content .\result.txt | Select -First 1
      
    - name: Save on a temporary variable
      shell: powershell
      run: |
        $PACKAGENAMETOPUBLISH=Get-Content .\result.txt | Select -First 1
        $PACKAGENAMETOPUBLISH
        
    - name: Publish Nuget package
      shell: powershell
      run: |
        dotnet nuget push $PACKAGENAMETOPUBLISH --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
